### ISSUE TITLE
problem with ontology prefix being switched to <http://www.semanticweb.org/owl/owlapi/turtle#

### ISSUE THREAD

**Issue by lechatpito** [utapyngo/owl2vcs#9]
In turtle, the diff tool seems to switch ontology prefix URI to `<http://www.semanticweb.org/owl/owlapi/turtle#`
so I get this kind of diff:

```
AnnotationAssertion(rdfs:label <http://www.semanticweb.org/owl/owlapi/turtle#17741> "idea")
- ClassAssertion(dextro:VisualConcept <http://www.semanticweb.org/owl/owlapi/turtle#10572>)
- Declaration(Class(<http://www.semanticweb.org/owl/owlapi/turtle#21822>))
```

Any idea if this is a bug or some config problem on my side?
Thanks

**Comment by izqs** [comment]
What is the original prefix?

**Comment by utapyngo** [comment]
What is the original prefix?

**Comment by lechatpito** [comment]
Thanks for your prompt answer, it looks like it was a problem on my side with the @base prefix.
And thank you for this useful tool.
